"""
PDF Blueprint Generator — Creates professional Quiet Eye blueprint PDF documents.
Uses ReportLab for PDF generation with a dark motorsport theme.
"""
import io
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm, cm
from reportlab.lib.colors import Color
from reportlab.pdfgen import canvas
from reportlab.lib.enums import TA_LEFT, TA_CENTER


# ── Theme Colors ─────────────────────────────────────────
CYAN = Color(0/255, 240/255, 255/255)
ORANGE = Color(255/255, 159/255, 28/255)
GREEN = Color(16/255, 185/255, 129/255)
PURPLE = Color(139/255, 92/255, 246/255)
RED = Color(239/255, 68/255, 68/255)
DARK_BG = Color(10/255, 10/255, 15/255)
CARD_BG = Color(22/255, 22/255, 30/255)
TEXT_PRIMARY = Color(230/255, 230/255, 235/255)
TEXT_MUTED = Color(150/255, 150/255, 160/255)
WHITE = Color(1, 1, 1)


def generate_blueprint_pdf(blueprint):
    """
    Generate a complete Quiet Eye Blueprint PDF.

    Args:
        blueprint: dict with trackName, vehicleType, corners[], protocol, etc.

    Returns: bytes (PDF file content)
    """
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    # Page 1: Title & Overview
    _draw_title_page(c, width, height, blueprint)

    # Pages 2+: Corner-by-corner details
    corners = blueprint.get('corners', [])
    for i, corner in enumerate(corners):
        c.showPage()
        _draw_corner_page(c, width, height, corner, i + 1, len(corners))

    # Final page: Training Protocol
    protocol = blueprint.get('protocol', {})
    if protocol:
        c.showPage()
        _draw_protocol_page(c, width, height, protocol, blueprint)

    c.save()
    buffer.seek(0)
    return buffer.getvalue()


def _draw_background(c, width, height):
    """Draw dark background."""
    c.setFillColor(DARK_BG)
    c.rect(0, 0, width, height, fill=1, stroke=0)


def _draw_footer(c, width, height, page_num, total_pages=None):
    """Draw page footer."""
    c.setFillColor(TEXT_MUTED)
    c.setFont("Helvetica", 8)
    c.drawString(20*mm, 10*mm, "Quiet Eye Blueprint — Generated by Lap Blueprint Generator")
    if total_pages:
        c.drawRightString(width - 20*mm, 10*mm, f"Page {page_num} of {total_pages}")


def _draw_title_page(c, width, height, blueprint):
    """Draw the title/overview page."""
    _draw_background(c, width, height)

    y = height - 40*mm

    # Title
    c.setFillColor(CYAN)
    c.setFont("Helvetica-Bold", 28)
    c.drawString(25*mm, y, "QUIET EYE BLUEPRINT")
    y -= 15*mm

    # Track name
    c.setFillColor(TEXT_PRIMARY)
    c.setFont("Helvetica-Bold", 18)
    track_name = blueprint.get('trackName', 'Unknown Track')
    c.drawString(25*mm, y, track_name)
    y -= 12*mm

    # Metadata
    c.setFillColor(TEXT_MUTED)
    c.setFont("Helvetica", 11)

    vehicle = blueprint.get('vehicleType', 'car').title()
    skill = blueprint.get('skillLevel', 'intermediate').title()
    client = blueprint.get('clientName', '')
    corner_count = blueprint.get('cornerCount', len(blueprint.get('corners', [])))
    date = datetime.now().strftime('%d %B %Y')

    info_lines = [
        f"Vehicle: {vehicle}",
        f"Skill Level: {skill}",
        f"Corners: {corner_count}",
        f"Generated: {date}",
    ]
    if client:
        info_lines.insert(0, f"Client: {client}")

    for line in info_lines:
        c.drawString(25*mm, y, line)
        y -= 7*mm

    y -= 10*mm

    # Divider
    c.setStrokeColor(Color(0.2, 0.2, 0.25))
    c.setLineWidth(0.5)
    c.line(25*mm, y, width - 25*mm, y)
    y -= 15*mm

    # The Four Cues
    c.setFillColor(CYAN)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(25*mm, y, "THE FOUR CUES")
    y -= 10*mm

    c.setFont("Helvetica", 10)
    cues = [
        ("1.", "Eyes Braking Marker — Aware Apex"),
        ("2.", "Eyes Apex — Aware Exit"),
        ("3.", "Eyes Exit — Aware Straight"),
        ("4.", "Eyes Straight — Aware Braking Marker"),
    ]
    for num, cue in cues:
        c.setFillColor(ORANGE)
        c.drawString(25*mm, y, num)
        c.setFillColor(TEXT_PRIMARY)
        c.drawString(35*mm, y, cue)
        y -= 7*mm

    y -= 10*mm

    # Overall Strategy (if available)
    protocol = blueprint.get('protocol', {})
    strategy = protocol.get('overallStrategy', '')
    if strategy:
        c.setFillColor(GREEN)
        c.setFont("Helvetica-Bold", 12)
        c.drawString(25*mm, y, "OVERALL STRATEGY")
        y -= 8*mm

        c.setFillColor(TEXT_PRIMARY)
        c.setFont("Helvetica", 10)
        # Word wrap
        lines = _wrap_text(strategy, 85)
        for line in lines:
            c.drawString(25*mm, y, line)
            y -= 6*mm

    y -= 8*mm

    key_principle = protocol.get('keyPrinciple', '')
    if key_principle:
        c.setFillColor(PURPLE)
        c.setFont("Helvetica-Bold", 12)
        c.drawString(25*mm, y, "KEY PRINCIPLE")
        y -= 8*mm

        c.setFillColor(TEXT_PRIMARY)
        c.setFont("Helvetica-Oblique", 10)
        lines = _wrap_text(key_principle, 85)
        for line in lines:
            c.drawString(25*mm, y, line)
            y -= 6*mm

    _draw_footer(c, width, height, 1)


def _draw_corner_page(c, width, height, corner, corner_idx, total_corners):
    """Draw a single corner detail page."""
    _draw_background(c, width, height)

    y = height - 30*mm

    # Corner header
    name = corner.get('name', f'Corner {corner_idx}')
    c.setFillColor(CYAN)
    c.setFont("Helvetica-Bold", 20)
    c.drawString(25*mm, y, f"Corner {corner.get('cornerNumber', corner_idx)}")
    y -= 8*mm

    c.setFillColor(TEXT_PRIMARY)
    c.setFont("Helvetica", 14)
    c.drawString(25*mm, y, name)
    y -= 10*mm

    # Corner metadata
    c.setFillColor(TEXT_MUTED)
    c.setFont("Helvetica", 10)
    direction = corner.get('direction', 'unknown')
    corner_type = corner.get('type', 'medium')
    severity = corner.get('severity', 'medium')
    difficulty = corner.get('qeDifficulty', 'moderate')

    meta = f"{direction.title()} {corner_type.title()} | Severity: {severity} | QE Difficulty: {difficulty}"
    c.drawString(25*mm, y, meta)
    y -= 12*mm

    # Weak corner flag
    if corner.get('isWeakCorner'):
        c.setFillColor(RED)
        c.setFont("Helvetica-Bold", 10)
        reason = corner.get('weakCornerReason', 'Requires extra repetitions')
        c.drawString(25*mm, y, f"WEAK CORNER: {reason}")
        y -= 10*mm

    # Gaze sequence
    gaze_seq = corner.get('gazeSequence', {})
    phases = [
        ('BRAKE MARKER VISIBLE', 'brakeMarkerVisible', CYAN),
        ('AT BRAKING', 'brake', CYAN),
        ('APEX', 'apex', GREEN),
        ('EXIT', 'exit', ORANGE),
        ('NEXT MARKER', 'nextMarker', PURPLE),
    ]

    for phase_label, phase_key, color in phases:
        phase = gaze_seq.get(phase_key, {})
        if not phase:
            continue

        eyes = phase.get('eyes', '')
        aware = phase.get('aware', '')

        if not eyes and not aware:
            continue

        # Phase header
        c.setFillColor(color)
        c.setFont("Helvetica-Bold", 11)
        c.drawString(25*mm, y, phase_label)
        y -= 7*mm

        # Eyes target
        if eyes:
            c.setFillColor(CYAN)
            c.setFont("Helvetica", 10)
            c.drawString(30*mm, y, f"Eyes: {eyes}")
            y -= 6*mm

        # Aware target
        if aware:
            c.setFillColor(ORANGE)
            c.setFont("Helvetica", 10)
            c.drawString(30*mm, y, f"Aware: {aware}")
            y -= 6*mm

        # Cue label
        cue_label = phase.get('cueLabel', '')
        if cue_label:
            c.setFillColor(TEXT_MUTED)
            c.setFont("Helvetica-Oblique", 9)
            c.drawString(30*mm, y, cue_label)
            y -= 6*mm

        y -= 3*mm

        # Check if we need a new page
        if y < 50*mm:
            _draw_footer(c, width, height, corner_idx + 1)
            c.showPage()
            _draw_background(c, width, height)
            y = height - 30*mm

    # Quiet Eye Cue
    qe_cue = corner.get('quietEyeCue', '')
    if qe_cue:
        y -= 5*mm
        c.setFillColor(GREEN)
        c.setFont("Helvetica-Bold", 10)
        c.drawString(25*mm, y, "QUIET EYE CUE")
        y -= 7*mm
        c.setFillColor(TEXT_PRIMARY)
        c.setFont("Helvetica-Oblique", 10)
        lines = _wrap_text(qe_cue, 80)
        for line in lines:
            c.drawString(30*mm, y, line)
            y -= 6*mm

    # Risk factors
    risks = corner.get('riskFactors', [])
    if risks:
        y -= 5*mm
        c.setFillColor(RED)
        c.setFont("Helvetica-Bold", 10)
        c.drawString(25*mm, y, "VAN RISK FACTORS")
        y -= 7*mm
        c.setFillColor(TEXT_PRIMARY)
        c.setFont("Helvetica", 9)
        for risk in risks[:3]:
            c.drawString(30*mm, y, f"• {risk}")
            y -= 6*mm

    # Coaching notes
    notes = corner.get('coachingNotes', '')
    if notes:
        y -= 5*mm
        c.setFillColor(TEXT_MUTED)
        c.setFont("Helvetica-Oblique", 9)
        lines = _wrap_text(notes, 85)
        for line in lines:
            c.drawString(25*mm, y, line)
            y -= 5*mm

    _draw_footer(c, width, height, corner_idx + 1)


def _draw_protocol_page(c, width, height, protocol, blueprint):
    """Draw the training protocol page."""
    _draw_background(c, width, height)

    y = height - 30*mm

    # Title
    c.setFillColor(CYAN)
    c.setFont("Helvetica-Bold", 22)
    c.drawString(25*mm, y, "TRAINING PROTOCOL")
    y -= 15*mm

    # Training protocol
    tp = protocol.get('trainingProtocol', protocol)
    daily = tp.get('dailyMinutes', 15)

    c.setFillColor(TEXT_PRIMARY)
    c.setFont("Helvetica", 11)
    c.drawString(25*mm, y, f"Daily Training: {daily} minutes")
    y -= 12*mm

    # Steps
    steps = tp.get('steps', [])
    for step in steps:
        title = step.get('title', '')
        instruction = step.get('instruction', '')
        duration = step.get('duration', '')

        c.setFillColor(GREEN)
        c.setFont("Helvetica-Bold", 11)
        c.drawString(25*mm, y, title)

        c.setFillColor(TEXT_MUTED)
        c.setFont("Helvetica", 9)
        if duration:
            c.drawRightString(width - 25*mm, y, duration)
        y -= 7*mm

        c.setFillColor(TEXT_PRIMARY)
        c.setFont("Helvetica", 10)
        c.drawString(30*mm, y, instruction)
        y -= 10*mm

    # Weak corner drills
    weak_drills = tp.get('weakCornerDrills', '')
    if weak_drills:
        y -= 5*mm
        c.setFillColor(ORANGE)
        c.setFont("Helvetica-Bold", 12)
        c.drawString(25*mm, y, "WEAK CORNER DRILLS")
        y -= 8*mm

        c.setFillColor(TEXT_PRIMARY)
        c.setFont("Helvetica", 10)
        lines = _wrap_text(weak_drills, 85)
        for line in lines:
            c.drawString(25*mm, y, line)
            y -= 6*mm

    # Per-corner lookAndCall
    corner_protocols = protocol.get('corners', [])
    if corner_protocols:
        y -= 10*mm
        c.setFillColor(CYAN)
        c.setFont("Helvetica-Bold", 12)
        c.drawString(25*mm, y, "LOOK AND CALL SCRIPTS")
        y -= 10*mm

        for cp in corner_protocols:
            num = cp.get('number', '?')
            calls = cp.get('lookAndCall', [])
            speed_ramp = cp.get('speedRamp', '')

            c.setFillColor(ORANGE)
            c.setFont("Helvetica-Bold", 10)
            c.drawString(25*mm, y, f"Corner {num}")
            if speed_ramp:
                c.setFillColor(TEXT_MUTED)
                c.setFont("Helvetica", 9)
                c.drawString(55*mm, y, f"Speed: {speed_ramp}")
            y -= 7*mm

            c.setFillColor(TEXT_PRIMARY)
            c.setFont("Helvetica", 9)
            for call in calls:
                c.drawString(30*mm, y, f"→ {call}")
                y -= 5.5*mm

            y -= 3*mm

            if y < 40*mm:
                _draw_footer(c, width, height, 99)
                c.showPage()
                _draw_background(c, width, height)
                y = height - 30*mm

    total_pages = len(blueprint.get('corners', [])) + 2
    _draw_footer(c, width, height, total_pages, total_pages)


def _wrap_text(text, max_chars=80):
    """Simple word-wrap text to max_chars per line."""
    words = text.split()
    lines = []
    current = ""
    for word in words:
        if len(current) + len(word) + 1 <= max_chars:
            current = f"{current} {word}" if current else word
        else:
            if current:
                lines.append(current)
            current = word
    if current:
        lines.append(current)
    return lines
